.gitignore, README.md, tap_mongodb/__init__.py
Fix `replication_method` -> `replication-method` catalog config typo
=> Fix replication_method -> replication-method catalog config typo

tap_mongodb/__init__.py
Adds handling for all roles with the following behavior:
- Discover all databases if user has one of these roles:
- `root`
- `readAnyDatabase`,
- `readWriteAnyDatabase`
- Discover only corresponding database with these roles:
- `read`
- `readWrite`
- `dbOwner` 
- `backup`
- Ignores these roles:
- `dbAdmin`
- `userAdmin`
- `clusterAdmin`
- `clusterManager`
- `clusterMonitor`
- `hostManager` 
- `restore`
Otherwise, assume it is a custom role, and get the roleInfo to see what roles the custom role contains.
=> handle all types of mongo roles

CHANGELOG.md, setup.py
Version bump from #25 
N/A
N/A
- revert #25 
- bump version to 0.2.3
- re-release to pypi
=> Version 0.2.2

CHANGELOG.md, setup.py
Version bump to 0.3.0
N/A
- Revert #27 and bump patch version
=> Version 0.3.0 and changelog

CHANGELOG.md, setup.py
Testing has completed, releasing current code as a major version 1.
Medium, any issues not uncovered in testing will need to be weighed against a major version from this point on.
- No rollback, all changes will be fixes on this Major moving forward.
=> Version 1.0.0

CHANGELOG.md, setup.py
=> bump version to 1.0.1

tap_mongodb/sync_strategies/common.py
Add support for DBRef (MongoDB [docs](https://docs.mongodb.com/manual/reference/database-references/))
- [Added tap-tester test](https://github.com/stitchdata/tap-tester/pull/170) and ensured that it passed with this change
- Cloned connection that was failing because one of their collections had a DBRef -- this change unblocked the connection.
None
=> add support for dbrefs

CHANGELOG.md, setup.py
=> bump version to 1.0.2

CHANGELOG.md, setup.py
=> bump version to 1.0.3

tap_mongodb/__init__.py
https://stitchdata.atlassian.net/browse/SRCE-2046
- Low, if your config has `"ssh": "true"` and `"ssl":"true"`, the tap will fail.
=> SRCE-2046: Turn off cert validation if using ssl and ssh tunnel

CHANGELOG.md, setup.py
Version bump PR for #36 
- See #36 
- Low, see #36 
- revert #36 and bump the version
=> Bump version, update changelog

CHANGELOG.md, setup.py
=> bump version to 2.0.0

tap_mongodb/__init__.py
=> Singer duplicate db discovery

CHANGELOG.md, setup.py
bumped patch version to 2.0.1
low
=> bumped patch version to 2.0.1

.circleci/config.yml, tests/test_mongodb_datatype.py, tests/test_mongodb_discovery.py, tests/test_mongodb_full_table.py, tests/test_mongodb_full_table_id.py, tests/test_mongodb_full_table_interruptible.py, tests/test_mongodb_incremental.py, tests/test_mongodb_oplog.py, tests/test_mongodb_oplog_aged_out.py, tests/test_mongodb_projection.py
https://jira.talendforge.org/browse/TDL-14782
We updated tap-tester image in the configfile to point to stitch-tap-tester, which is the latest tap-tester image
- the tests running in circleci should give us a good idea about if this worked
- low, this is only for tap-tester
=> updated tap-tester image in config file to use stitch-tap-tester

.circleci/config.yml, Makefile
Get Mongo passing on 3.5.6 by adding dependencies and some exceptions to pylint.
- N/A
=> Update circle image

tests/test_mongodb_incremental_open_transactions.py
Created incremental open transaction test to validate taps behavior while in open transaction.
- execute tests/test_mongodb_incremental_open_transactions.py
=> added a test to validate tap behaviour in open transaction

tests/test_mongodb_incremental_open_transactions.py
=> modified the test based on PR feedback

tests/test_mongodb_table_reset_inc.py, tests/test_mongodb_table_reset_log.py
Add table reset cases for incremental and logical
=> Table reset cases for incremental and logical

tests/test_mongodb_id_pk_variations.py
Added test to cover edge case for pk variations
- execute the test - test_mongodb_id_pk_variations.py
=> added test to cover edge case pk variations

tests/test_mongodb_cname_restrictions.py, tests/test_mongodb_fname_restrictions.py, tests/test_mongodb_namespace_restrictions.py
Add 3 edge test cases for field name, collection name, and namespace length restrictions.
=> Add 3 name restriction edge cases

tests/test_mongodb_views.py
test to validate if views are being discovered
run the test - test_mongodb_views.py
=> test to validate if views are being discovered

tests/test_mongodb_configurable_properties.py
test the additional configurable properties for tap-mongodb
execute -  tests/test_mongodb_configurable_properties.py
=> Added test to validate additional configurable properties

.circleci/config.yml
modified slack notification format in circleci config
=> modified slack notification format in circleci config

.circleci/config.yml, tests/test_mongodb_cname_restrictions.py, tests/test_mongodb_configurable_properties.py, tests/test_mongodb_datatype.py, tests/test_mongodb_discovery.py, tests/test_mongodb_fname_restrictions.py, tests/test_mongodb_full_table.py, tests/test_mongodb_full_table_id.py, tests/test_mongodb_full_table_interruptible.py, tests/test_mongodb_id_pk_variations.py, tests/test_mongodb_incremental.py, tests/test_mongodb_incremental_open_transactions.py, tests/test_mongodb_index.py, tests/test_mongodb_log_based_interruptible.py, tests/test_mongodb_name_restrictions.py, tests/test_mongodb_namespace_restrictions.py, tests/test_mongodb_oplog.py, tests/test_mongodb_oplog_aged_out.py, tests/test_mongodb_oplog_bookmarks.py, tests/test_mongodb_projection.py, tests/test_mongodb_table_reset_inc.py, tests/test_mongodb_table_reset_log.py, tests/test_mongodb_views.py
Remove singer imports, start general import clean up, fix yml style
=> Remove singer imports, start general import clean up, fix yml style

CHANGELOG.md, setup.py
This is the version bump PR for #95 
See #95  
See #95 
- revert #95 and bump the version
=> Bump to `v2.1.3`, update changelog

.circleci/config.yml, Makefile, setup.py, tap_mongodb/__init__.py, tap_mongodb/sync_strategies/common.py, tests/mongodb_common.py, tests/test_mongodb_datatype.py, tests/test_mongodb_fname_restrictions.py, tests/test_mongodb_incremental.py, tests/test_mongodb_incremental_open_transactions.py, tests/test_mongodb_name_restrictions.py, tests/test_mongodb_projection.py, tests/test_mongodb_table_reset_inc.py
1) Upgrade pymongo to 4.4.0
2) Added condition to handle DatetimeMS binary date values.
- Low risk
=> TDL-22154 : Upgrade PyMongo to v4.3+

bin/test-db, tests/test_mongodb_cname_restrictions.py, tests/test_mongodb_fname_restrictions.py, tests/test_mongodb_name_restrictions.py, tests/test_mongodb_namespace_restrictions.py, tests/test_mongodb_oplog.py
TDL-20088 updates to field, collection, and namespace restriction tests
=> TDL-20088 updates to field, collection, and namespace restriction tests

CHANGELOG.md, setup.py, tap_mongodb/sync_strategies/oplog.py
To encounter issue #109 of the cursor/session timeout. 
=> Refresh the session every 10 minutes during oplog queries

.circleci/config.yml, CHANGELOG.md, setup.py
=> Upgrades for python 3.11

CHANGELOG.md, setup.py
bump version changes in CHANGELOG.md and setup.py for PR https://github.com/singer-io/tap-mongodb/pull/94
=> Bump 3.1.2

CHANGELOG.md, setup.py, tap_mongodb/__init__.py, tap_mongodb/sync_strategies/common.py
removes deprecated terminaltables dependency. sync summary is replaced with plain logging. 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
=> remove deprecated terminaltables dependency

CHANGELOG.md
Adds a changelog entry for #121 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
=> Changelog entry for PR 121
