- setup.py
Update `singer-python==5.3.3` dependency
`singer-python==5.3.3` now includes a fix for Windows and `strftime`, https://github.com/singer-io/singer-python/pull/87
> Update singer-python==5.3.3 dependency

- tap_mongodb/__init__.py
Fix https://github.com/singer-io/tap-mongodb/issues/1
`user`/`pass` in `config.json` should be optional because access control is optional.
> By default mongodb has no enabled access control, so there is no default user or password.
>
> https://stackoverflow.com/a/38921949/796832
Here are some other docs on enabled access control, https://docs.mongodb.com/manual/tutorial/enable-authentication/
> Update config to have optional user/pass

- tap_mongodb/__init__.py
- tap_mongodb/sync_strategies/common.py
- tap_mongodb/sync_strategies/incremental.py
- If replication key changes, wipe state and resync collection
- Only support `datetime`, `timestamp`, `int`, and `ObjectId` replication key types
- Only discover databases that the user has read access to
> Updates & Bug Fixes

- tap_mongodb/__init__.py
Some edge cases came in where the projection was either `''` or `'""'`
> Fix for empty string projection

- tap_mongodb/sync_strategies/common.py
- tap_mongodb/sync_strategies/oplog.py
We've received feedback that querying the oplog with `ts` (timestamp), `ns` (collection namespace), and `op` (operation) filters leads to a heavy cpu load on the mongo cluster being queried.  To resolve this, we've done the following:
- Removed the `ns` and `op` filters from the mongo query and filtered out the unwanted results in the tap
- Added the `oplog_replay=True` flag to oplog queries IF there is no projection being used.
- `oplog_replay` is an internal optimization for oplog queries with a filter on `ts`
- If `oplog_replay=True`, the projection is disregarded.  This MongoDB [Jira Ticket](https://jira.mongodb.org/browse/SERVER-34096) seems to validate this finding
This PR also adds assertions around the range and ordering of the oplog results.
> Oplog sync performance enhancements

- tap_mongodb/sync_strategies/common.py
JIRA: https://stitchdata.atlassian.net/browse/SUP-880
The issue being solved here is that `pymongo` will return a `datetime` object with invalid values that then fails our transformation code. Two changes have been made:
- In the event that year is `0`, the value will be manually formatted into an ISO-8601 format without being localized. This is because the lack of support for year `0` is Python specific, and would be better handled downstream.
- In the event that formatting datetimes fails for any other reason, the tap will raise an exception with an informative message that gives the `tap_stream_id`, Object ID, path to the value, and the value itself.
- Added case to datatyping integration test
- Awaiting passing of existing automation
- Manually verified that all path construction code …
> Improved DateTime Handling and Messaging

- tap_mongodb/sync_strategies/common.py
https://stitchdata.atlassian.net/browse/SUP-893
UUID fields would come through the tap as a `uuid.UUID` data type which was not matched in the existing replication key conversion functions, nor the value transformation.
This PR adds cases to each of those portions of the tap, for all sync strategies.
- N/A all cases covered by automation
Change is additive, very low chance of extra issues.
> Added Support for UUID

- bin/test-db
- tap_mongodb/__init__.py
- tap_mongodb/sync_strategies/common.py
1. Remove `admin` from the discovery blacklist, allowing the tap to discover collections in the `admin` db
2. Add support for replication keys of type Int64.
- Cloned connections and verified that this resolved the issue for both (1) and (2)
None
> Discover collections in `admin` db and support Int64 replication keys

- tap_mongodb/sync_strategies/common.py
Added `float` as a supported replication key type
- Added a tap-tester test around this that failed before this change and passed after
n/a
> add float as a supported replication key

- tap_mongodb/__init__.py
Change verify mode to be an optional config argument, instead of assuming that using an SSH tunnel invalidates the Subject of the SSL cert verification.
`verify_mode` defaults to `"true"` and removing it will disable Certificate Name verification on the connection. This is useful if you have a self-signed cert attached to your mongo instance or for some other network topological reason the name verification doesn't apply.
- None. Relying on automation to run through the code and confirm that this has no effect on existing configs.
Low, this is an additive optional property. In most cases it should have no effect.
> Add verify mode option to config

- Makefile
- tap_mongodb/__init__.py
- tap_mongodb/sync_strategies/common.py
- tap_mongodb/sync_strategies/full_table.py
- tap_mongodb/sync_strategies/incremental.py
- tap_mongodb/sync_strategies/oplog.py
- tests/test_common.py
- For each record that comes through, recursively walk it and "build" a running schema by:
- Write `"type": "string", "format": "date-time"` for date-time fields
- Write `"type": "number", "multipleOf": 1e-34` for decimal fields (mongo bson decimal128 has 34 units of precision: [docs](https://docs.mongodb.com/manual/core/shell-types/#numberdecimal))
- Write `"type": "number"` for float fields
- If the schema changes as a result of the current record, write a schema message with the updated schema
- Track the amount of time spent building schemas and include it in summary at the end of each run
- Added unit tests for `row_to_schema` function
- tap-tester tests still pass
- tested on connections that were experiencing date-times being loaded as strings and column splitting for doubles, and …
> Build and Write Schemas

- .circleci/config.yml
- tap_mongodb/__init__.py
- tap_mongodb/sync_strategies/common.py
- tests/test_mongodb_full_table_id.py
- tests/test_mongodb_full_table_interruptible.py
- tests/test_mongodb_oplog_aged_out.py
Get pylint passing by addressing `raise-missing-from` error.
** Update **
Use v4 tap-tester image, add circleci context-user.
Change tap_name in some tests to get virtual env built correctly.
Added 
- Minimal, explicitly specifying exception using from. If implemented incorrectly could cause an unintended exception to be raised.
> specify from in exceptions, get pylint to pass

- .circleci/config.yml
Use tap_tester_sandbox env, move build time to avoid collisions.
> move build time, use proper env

- tap_mongodb/__init__.py
- tap_mongodb/sync_strategies/oplog.py
- tests/test_mongodb_oplog_bookmarks.py
This PR writes a bookmark for oplog streams that don't sync records.
This is to prevent the scenarios where a collection doesn't get very many updates and the bookmark we have in state goes stale.
> Advance the oplog bookmark when no records are synced

- CHANGELOG.md
- setup.py
- tap_mongodb/__init__.py
- tap_mongodb/sync_strategies/oplog.py
- tests/test_mongodb_oplog_bookmarks.py
Currently we traverse all new oplog changes for each collection, once per collection. This change makes it so we only traverse entries for the current collection.
WIP: this breaks bookmark logic.
> Include collection name in oplog query

- .circleci/config.yml
- CHANGELOG.md
- setup.py
TDL-19353: pymongo driver issue
- Upgraded pymongo to the version `3.12.3`
- 3.8 -> PyMongo supports MongoDB 2.6, 3.0, 3.2, 3.4, 3.6 and 4.0.
- 3.12.3 -> PyMongo supports MongoDB 2.6, 3.0, 3.2, 3.4, 3.6, 4.0, 4.2, 4.4, and 5.0.
- 4.1.1 -> PyMongo supports MongoDB 3.6, 4.0, 4.2, 4.4, and 5.0.
- As per this [document](https://www.mongodb.com/docs/atlas/reference/serverless-instance-limitations/#minimum-driver-versions-for-serverless-instances) the minimum pymongo version requirement for serverless instance is `3.12.0`
> TDL-19353: pymongo driver issue

- .circleci/config.yml
Changes the circleci images to `stitch-tap-tester-18.04` now that `stitch-tap-tester` now uses ubuntu 22.04.
This tap is pinned to python 3.5.6, which is incompatible with 22.04.
- Low, `stitch-tap-tester-18.04` is the same image as it was previously using.
> update tap-tester to the 18.04 image

- tap_mongodb/sync_strategies/full_table.py
This PR adds the use of a projection to the query that fetches the max `_id` from a collection. This allows the document we fetch to contain bad BSON data, but if we don't care to replicate the bad data, the tap won't try to decode those bytes and blow up
This approach was picked over the use of initializing the `MongoClient` with `unicode_decode_error_handler='ignore'` because I think it's valuable to know when non-UTF-8 encoded data has been inserted into Mongo for data we want to sync.
- Ran the tap before and after the change to confirm it works
- Low, this unblocks people and doesn't loosen the checks on the data
> Use a projection if we have one

- CHANGELOG.md
- setup.py
- tap_mongodb/__init__.py
PyMongo 4 automatically discovers replica sets. When going through an SSH tunnel, these replica sets are not accessible.
Setting `directConnection=True` allows PyMongo to connect directly to a single MongoDB node.
https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html#directconnection-defaults-to-false
- Connection through an SSH tunnel no longer gets `ServerSelectionTimeoutError`
Low. This will match the functionality of PyMongo 3, where the default behavior was to connect to a single server.
> add directConnection connection param

- CHANGELOG.md
- setup.py
- tap_mongodb/__init__.py
This PR updates one of the keys according to the [PyMongo 4 Migration Guide](https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html#renamed-uri-options).
> Instead of ssl.CERT_NONE, ssl.CERT_OPTIONAL and ssl.CERT_REQUIRED, the new option expects a boolean value - True is equivalent to ssl.CERT_NONE, while False is equivalent to ssl.CERT_REQUIRED.
- Low. This was a breaking change to PyMongo 3 and we should have done this in #99 
- revert this branch, bump the version
> TDL-24216 Rename URI options

- CHANGELOG.md
- setup.py
- tap_mongodb/sync_strategies/oplog.py
Some mongoDB servers are not supporting sessions. If they do not support sessions then gracefully revert to prior behavior without using a session and don't send the "keep-alive" message.
> Gracefully handle the mongo server not supporting sessions

- Makefile
Add use-yield-from to pylint disables list to allow build success
> Update pylint disables March 2024

- tap_mongodb/sync_strategies/oplog.py
Fixes issue - #93
The change allows user to specify string projection, instead of just integer values 
A sample projection that didn't work before and should be working after merging this PR
`{"name": "$personName"}`
> sum string projection as integer of bool

- setup.py
- Bumps pymongo to latest version (at time of writing) `4.10.1`
- Bumps tap version to `3.1.4`
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
> TDL-26885: Bump pymongo for veracode & dependabot
